# Generated by Django 4.1.3 on 2022-12-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Whiskey', 'Whiskey'), ('Tequilla', 'Tequilla'), ('Rum', 'Rum'), ('Wine', 'Wine'), ('Vodka', 'Vodka'), ('Liquer', 'Liquer')], max_length=40),
        ),
    ]
