# Generated by Django 4.1.3 on 2022-12-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customuser_remove_orders_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=False, max_length=30, unique=True),
        ),
    ]
