# Generated by Django 4.1.3 on 2023-01-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_contact_order_stripepayment_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
