# Generated by Django 4.1.3 on 2023-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(to='store.cart'),
        ),
    ]
